name: ABMCFly
main: com.moneybags.tempfly.TempFly
softdepend: [Factions, ASkyBlock, Essentials, MVdWPlaceholderAPI, PlaceholderAPI, aSkyBlock, Vault, WorldGuard, WorldEdit, IridiumSkyblock, BentoBox, SuperiorSkyblock2]
api-version: 1.20
version: 3.1.8
commands:
    tempfly:
        description: base command
        aliases: [tfly, tf]